BAD_WORDS = {
    "ass", "asshole", "bastard", "bitch", "bloody", "bollocks", "bullshit", "cocksucker",
    "crap", "cunt", "damn", "dick", "dickhead", "douche", "dumb", "faggot", "fuck", "fucker",
    "goddamn", "idiot", "jackass", "jerk", "kike", "loser", "moron", "motherfucker",
    "nazi", "nigga", "nigger", "paki", "piss", "prick", "pussy", "queer", "retard", "shit",
    "shithead", "slut", "suck", "twat", "whore", "wanker", "yank", "zoophile", "dyke",
    "chink", "spic", "beaner", "raghead", "sandnigger", "gyppo", "gypsy", "gook", "jap",
    "nip", "coon", "tarbaby", "redskin", "ape", "sambo", "jungle", "bunny", "camel", "jockey",
    "infidel", "heathen", "zionist", "kafir", "crusader", "muzzie", "towelhead", "yid",
    "tranny", "fag", "shemale", "manwhore", "feminazi", "dykes", "slattern", "hebitch",
    "cockmonger", "whorebag", "manslut", "skank", "slag", "cumdumpster", "twink",
    "rat", "cockroach", "parasite", "vermin", "scum", "filth", "disease", "virus", "cancer",
    "plague", "garbage", "trash", "mutant", "creature", "animal", "monster", "zombie",
    "demon", "ghoul", "subhuman", "inhuman", "freak", "savage",
    "kill", "rape", "lynch", "murder", "stab", "shoot", "burn", "bomb", "execute",
    "eliminate", "gas", "slaughter", "torture", "blow", "wipe", "choke", "hang",
    "death", "invade", "overrun", "purge", "exterminate", "cleanse", "destroy", "occupy",
    "gang", "war", "cleansing", "jihadist", "infestation", "genocide", "terrorist",
    "fool", "imbecile", "twit", "nincompoop", "simpleton", "dunce", "brute", "cretin",
    "nitwit", "halfwit", "fatass", "ugly", "disgusting", "repulsive", "gross", "retarded",
    "degenerate", "delusional", "brainwashed", "scumbag", "sicko", "psycho", "maniac",
    "subhuman", "filthy", "useless", "unwanted", "burden", "pest", "pestilence", "horde",
    "swarm", "scourge", "menace", "evil", "vermin", "invader", "demonic", "hostile",
    "cancerous", "bastards", "shitbag", "whoremonger", "cumslut", "dicknose", "shitstain", 
    "cockroach", "fartface", "buttfuck", "dickcheese", "wasteman", "assbiscuit", "shitcock", 
    "shitheel", "jackwagon", "turdburglar", "turd", "buttknuckle", "shitmuncher", "buttmonkey", 
    "slutshame", "pussylicker", "nutmuncher", "buttfuckery", "cumguzzler", "fartsucker", 
    "coochie", "ballsniffer", "cockknocker", "assweasel", "dickwad", "pissflap", "ballbag", 
    "cumrag", "twatwaffle", "dirtywhore", "cockroach", "dildo", "poopface", "testicleface", 
    "cockslut", "shithound", "cockpocket", "nutbar", "biscuithead", "shitlicker", "buttflap", 
    "cuck", "cumble", "shitguzzler", "titfucker", "stankpussy", "pisshead", "spermdump", 
    "diarrheahead", "dumbass", "assclown", "bagofpiss", "turdbrain", "septichead", "cockwomble", 
    "jizzmonkey", "turdpile", "cumbucket", "squeakymouth", "slutbaby", "assgoblin", "shitforbrains",
    "chickenfucker", "wanksta", "prickhead", "fuckboi", "sexybutt", "dickbitch", "cockbag", 
    "filthbucket", "shitdick", "slimeball", "assclapper", "dickface", "skunkpussy", "fuckface", 
    "assmuncher", "ballsweat", "whoreface", "foolfucker", "whorebag", "smutmouth", "shitbitch", 
    "pissbrain", "wankjob", "cockface", "godfucker", "dickshot", "shitstorm", "cockball", 
    "shitwhore", "jackoff", "slutkiss", "pisswhore", "fuckpile", "prickbitch", "buttplug", 
    "cocksniffer", "shithole", "slimewhore", "nutwaster", "spunkbucket", "fucktrap", 
    "cumburden", "pussyboy", "jerkbag", "slutbrain", "mughead", "wankcock", "assfucker", 
    "slutpuppy", "fartingcunt", "jizzpuddle", "buttdrop", "cockbreath", "bastardball", 
    "cockhead", "bastardface", "cuntbox", "twinkhole", "cockfuck", "cumface", "pissbitch", 
    "cuntpunch", "slutbitch", "assholebucket", "shitbelt", "buttfucket", "twatknuckle", 
    "fuckknob", "cumguzzler", "twatmonkey", "shitfaced", "jizzhead", "whorebasket", 
    "fuckyourmom", "whoreprick", "spunkbucket", "twatsucker", "pissball", "cockwatcher", 
    "cockballbag", "cocksnob", "bastardwhore", "fuckingdickhead", "sweatball", "bastardcock", 
    "titlicker", "cockchamp", "dickwater", "poopmouth", "fartsheep", "faggotball", "pissface", 
    "slutbag", "dickrider", "faggotweasel", "shitstew", "jerkfish", "cockdancer", 
    "prickflap", "whorehole", "cockroto", "fuckbuddy", "cockhanger", "turdfuck", 
    "bastardmouth", "cumbinator", "prickhole", "cockteaser", "buttblaster", "twatass", 
    "whoremonger", "cocknugget", "diarrheaprince", "twatslime", "prickpuddle", "pissjerk"
}
